### ISSUE TITLE
exception raised - cannot load such file -- ACIrb/top.rb

### ISSUE THREAD

**Issue by jedelman8** [datacenter/acirb#2]
I'm able to launch the web UI, but it doesn't display any data.  It states "Table has no columns."

On the terminal, it keeps looping through and displays this:

```
scheduler caught exception:
cannot load such file -- ACIrb/top.rb
/var/lib/gems/1.9.1/gems/acirb-1.1.1.1/lib/naming.rb:71:in `get_mo_from_dn'
/var/lib/gems/1.9.1/gems/acirb-1.1.1.1/lib/loader.rb:56:in `load_hash'
/var/lib/gems/1.9.1/gems/acirb-1.1.1.1/lib/loader.rb:48:in `load_json'
/var/lib/gems/1.9.1/gems/acirb-1.1.1.1/lib/restclient.rb:194:in `block in parse_response'
/var/lib/gems/1.9.1/gems/acirb-1.1.1.1/lib/restclient.rb:193:in `each'
/var/lib/gems/1.9.1/gems/acirb-1.1.1.1/lib/restclient.rb:193:in `parse_response'
/var/lib/gems/1.9.1/gems/acirb-1.1.1.1/lib/restclient.rb:146:in `get'
/var/lib/gems/1.9.1/gems/acirb-1.1.1.1/lib/restclient.rb:216:in `query'
/home/cisco/acirb/examples/acidashboard/jobs/apic.rb:85:in `update_endpoint_chart'
/home/cisco/acirb/examples/acidashboard/jobs/apic.rb:210:in `block in <top (required)>'
/var/lib/gems/1.9.1/gems/rufus-scheduler-2.0.24/lib/rufus/sc/jobs.rb:230:in `call'
/var/lib/gems/1.9.1/gems/rufus-scheduler-2.0.24/lib/rufus/sc/jobs.rb:230:in `trigger_block'
/var/lib/gems/1.9.1/gems/rufus-scheduler-2.0.24/lib/rufus/sc/jobs.rb:204:in `block in trigger'
/var/lib/gems/1.9.1/gems/rufus-scheduler-2.0.24/lib/rufus/sc/scheduler.rb:430:in `call'
/var/lib/gems/1.9.1/gems/rufus-scheduler-2.0.24/lib/rufus/sc/scheduler.rb:430:in `block in trigger_job'

```

I imagine it's trying to load `top.rb` here:

```
 ACIrb.autoload('TopInfo', 'ACIrb/top.rb')
  ACIrb.autoload('TopMetaInf', 'ACIrb/top.rb')
  ACIrb.autoload('TopRoot', 'ACIrb/top.rb')
  ACIrb.autoload('TopRsMonPolSystemPolCons', 'ACIrb/top.rb')
  ACIrb.autoload('TopRsNeighFw', 'ACIrb/top.rb')
```

Newer to Ruby, so I don't want to mess around too much :)   Let me know what you think.

BTW, I'm on dCloud Version: 1.0(3f)

Anyconnect (active for the next day or so if you feel like testing against my system):
un: v805user3
pw: 1cd2ee

Thanks,
Jason

**Comment by paullesiak** [comment]
Jason, I will look into this more closely next week when back from PTO, however, could you please install 1.0.4.1 (gem install acirb -v 1.0.4.1)? I just want to rule out a model compatibility issue here.

Thanks
Paul

**Comment by jedelman8** [comment]
I thought I tried that, but realize my error is showing 1.1.1.1.

I ran `gem uninstall acirb` and removed all versions.  

Then, ran `gem install acirb -v 1.0.4.1` - installed fine.

Then, when running `bundle` again, it automatically downloaded 1.1.1.1!!!!

```
This was right after installing 1.0.4.1:
cisco@onepk:~/acirb/examples/acidashboard$ dashing start
Could not find acirb-1.1.1.1 in any of the sources
Run `bundle install` to install missing gems.
```

So then I ran bundle again:

```
cisco@onepk:~/acirb/examples/acidashboard$ bundle
Fetching gem metadata from https://rubygems.org/...........
Fetching version metadata from https://rubygems.org/...
Fetching dependency metadata from https://rubygems.org/..
Using httpclient 2.6.0.1
Using json 1.8.3
Using mini_portile 0.6.2
Using nokogiri 1.6.6.2
Using websocket 1.2.2
Installing acirb 1.1.1.1   <<<<<<<<<< auto-install of 1.1.1.1 
Using backports 3.6.6
Using coffee-script-source 1.9.1.1
Using execjs 2.0.2
Using coffee-script 2.2.0
Using daemons 1.2.3
Using rack 1.5.5
Using thread_safe 0.3.5
Using tzinfo 1.2.2
Using rufus-scheduler 2.0.24
Using sass 3.2.19
Using rack-protection 1.5.3
Using tilt 1.4.1
Using sinatra 1.4.6
Using multi_json 1.11.2
Using rack-test 0.6.3
Using sinatra-contrib 1.4.6
Using hike 1.2.3
Using sprockets 2.10.2
Using eventmachine 1.0.8
Using thin 1.6.3
Using thor 0.18.1
Using dashing 1.3.4
Using bundler 1.10.6
Bundle complete! 2 Gemfile dependencies, 29 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
cisco@onepk:~/acirb/examples/acidashboard$ 
cisco@onepk:~/acirb/examples/acidashboard$ dashing start
Connecting to APIC https://apic
Thin web server (v1.6.3 codename Protein Powder)
Maximum connections set to 1024
Listening on 0.0.0.0:3030, CTRL+C to stop
Updating interface stats
127.0.0.1 - - [03/Sep/2015 05:57:43] "GET /aci HTTP/1.1" 200 3326 0.0384
127.0.0.1 - - [03/Sep/2015 05:57:46] "GET /views/google_pie.html HTTP/1.1" 200 68 0.0009
127.0.0.1 - - [03/Sep/2015 05:57:46] "GET /views/list.html HTTP/1.1" 200 493 0.0010
127.0.0.1 - - [03/Sep/2015 05:57:46] "GET /views/number.html HTTP/1.1" 200 343 0.0008
127.0.0.1 - - [03/Sep/2015 05:57:46] "GET /views/graph.html HTTP/1.1" 200 167 0.0008
Updating count of end point types
Updating health and endpoint count
================================================================================
scheduler caught exception:
cannot load such file -- ACIrb/top.rb
/var/lib/gems/1.9.1/gems/acirb-1.1.1.1/lib/naming.rb:71:in `get_mo_from_dn'
/var/lib/gems/1.9.1/gems/acirb-1.1.1.1/lib/loader.rb:56:in `load_hash'
/var/lib/gems/1.9.1/gems/acirb-1.1.1.1/lib/loader.rb:48:in `load_json'
/var/lib/gems/1.9.1/gems/acirb-1.1.1.1/lib/restclient.rb:194:in `block in parse_response'
/var/lib/gems/1.9.1/gems/acirb-1.1.1.1/lib/restclient.rb:193:in `each'
/var/lib/gems/1.9.1/gems/acirb-1.1.1.1/lib/restclient.rb:193:in `parse_response'
/var/lib/gems/1.9.1/gems/acirb-1.1.1.1/lib/restclient.rb:146:in `get'
/var/lib/gems/1.9.1/gems/acirb-1.1.1.1/lib/restclient.rb:216:in `query'
/home/cisco/acirb/examples/acidashboard/jobs/apic.rb:85:in `update_endpoint_chart'
/home/cisco/acirb/examples/acidashboard/jobs/apic.rb:210:in `block in <top (required)>'
/var/lib/gems/1.9.1/gems/rufus-scheduler-2.0.24/lib/rufus/sc/jobs.rb:230:in `call'
/var/lib/gems/1.9.1/gems/rufus-scheduler-2.0.24/lib/rufus/sc/jobs.rb:230:in `trigger_block'
/var/lib/gems/1.9.1/gems/rufus-scheduler-2.0.24/lib/rufus/sc/jobs.rb:204:in `block in trigger'
/var/lib/gems/1.9.1/gems/rufus-scheduler-2.0.24/lib/rufus/sc/scheduler.rb:430:in `call'
/var/lib/gems/1.9.1/gems/rufus-scheduler-2.0.24/lib/rufus/sc/scheduler.rb:430:in `block in trigger_job'
================================================================================
================================================================================
```

**Comment by jedelman8** [comment]
Ever have a chance to take a look at this?

**Comment by paullesiak** [comment]
Jason, can you please modify Gemfile and change the line that says

```
gem 'acirb'
```

And add ,'1.0.4.1' to it, so it says

```
gem 'acirb', '1.0.4.1'
```

And run bundle again, then kick off dashing start? This will tell bundle to use the specific ACIrb gem version.

Also, what OS/ruby version are you running? I can't seem to replicate the issue on OS X/ruby2.0 with APIC 1.0.4o

**Comment by jedelman8** [comment]
Okay, that didn't work, but it is using 1.0.4.1 now.

Using ruby version 1.9.3 on Ubuntu 14.04.  Installed 2.0, but it still executed using 1.9.3.  Do you know how to force it to use 2.0?

```
Connecting to APIC https://apic
Thin web server (v1.6.3 codename Protein Powder)
Maximum connections set to 1024
Listening on 0.0.0.0:3030, CTRL+C to stop
Updating interface stats
Updating health and endpoint count
Updating count of end point types
================================================================================
scheduler caught exception:
cannot load such file -- ACIrb/top.rb
/var/lib/gems/1.9.1/gems/acirb-1.0.4.1/lib/naming.rb:71:in `get_mo_from_dn'
/var/lib/gems/1.9.1/gems/acirb-1.0.4.1/lib/loader.rb:56:in `load_hash'
/var/lib/gems/1.9.1/gems/acirb-1.0.4.1/lib/loader.rb:48:in `load_json'
/var/lib/gems/1.9.1/gems/acirb-1.0.4.1/lib/restclient.rb:194:in `block in parse_response'
/var/lib/gems/1.9.1/gems/acirb-1.0.4.1/lib/restclient.rb:193:in `each'
/var/lib/gems/1.9.1/gems/acirb-1.0.4.1/lib/restclient.rb:193:in `parse_response'
/var/lib/gems/1.9.1/gems/acirb-1.0.4.1/lib/restclient.rb:146:in `get'
/var/lib/gems/1.9.1/gems/acirb-1.0.4.1/lib/restclient.rb:216:in `query'
/var/lib/gems/1.9.1/gems/acirb-1.0.4.1/lib/restclient.rb:297:in `lookupByDn'
/home/cisco/acirb/examples/acidashboard/jobs/apic.rb:160:in `update_health'
/home/cisco/acirb/examples/acidashboard/jobs/apic.rb:197:in `block in <top (required)>'
/var/lib/gems/1.9.1/gems/rufus-scheduler-2.0.24/lib/rufus/sc/jobs.rb:230:in `call'
/var/lib/gems/1.9.1/gems/rufus-scheduler-2.0.24/lib/rufus/sc/jobs.rb:230:in `trigger_block'
/var/lib/gems/1.9.1/gems/rufus-scheduler-2.0.24/lib/rufus/sc/jobs.rb:204:in `block in trigger'
/var/lib/gems/1.9.1/gems/rufus-scheduler-2.0.24/lib/rufus/sc/scheduler.rb:430:in `call'
/var/lib/gems/1.9.1/gems/rufus-scheduler-2.0.24/lib/rufus/sc/scheduler.rb:430:in `block in trigger_job'
================================================================================
================================================================================
scheduler caught exception:
cannot load such file -- ACIrb/top.rb
/var/lib/gems/1.9.1/gems/acirb-1.0.4.1/lib/naming.rb:71:in `get_mo_from_dn'
/var/lib/gems/1.9.1/gems/acirb-1.0.4.1/lib/loader.rb:56:in `load_hash'
/var/lib/gems/1.9.1/gems/acirb-1.0.4.1/lib/loader.rb:48:in `load_json'
/var/lib/gems/1.9.1/gems/acirb-1.0.4.1/lib/restclient.rb:194:in `block in parse_response'
/var/lib/gems/1.9.1/gems/acirb-1.0.4.1/lib/restclient.rb:193:in `each'
/var/lib/gems/1.9.1/gems/acirb-1.0.4.1/lib/restclient.rb:193:in `parse_response'
/var/lib/gems/1.9.1/gems/acirb-1.0.4.1/lib/restclient.rb:146:in `get'
/var/lib/gems/1.9.1/gems/acirb-1.0.4.1/lib/restclient.rb:216:in `query'
/home/cisco/acirb/examples/acidashboard/jobs/apic.rb:85:in `update_endpoint_chart'
/home/cisco/acirb/examples/acidashboard/jobs/apic.rb:210:in `block in <top (required)>'
/var/lib/gems/1.9.1/gems/rufus-scheduler-2.0.24/lib/rufus/sc/jobs.rb:230:in `call'
/var/lib/gems/1.9.1/gems/rufus-scheduler-2.0.24/lib/rufus/sc/jobs.rb:230:in `trigger_block'
/var/lib/gems/1.9.1/gems/rufus-scheduler-2.0.24/lib/rufus/sc/jobs.rb:204:in `block in trigger'
/var/lib/gems/1.9.1/gems/rufus-scheduler-2.0.24/lib/rufus/sc/scheduler.rb:430:in `call'
/var/lib/gems/1.9.1/gems/rufus-scheduler-2.0.24/lib/rufus/sc/scheduler.rb:430:in `block in trigger_job'
================================================================================
```

**Comment by paullesiak** [comment]
I think I found the issue -- autoload was referencing the path as ACIrb/, and HFS+ is not case sensitive, however ext4 is, so under Linux the case was incorrect (trying to load ACIrb/ instead of acirb/).

I've uploaded a new gem 1.0.4.2 with the fix in place. Can you update the Gemfile one more time, pointing to 1.0.4.2 and give it another shot?

**Comment by jedelman8** [comment]
Yep!  Got it, and is working accordingly!

Thank you!

**Comment by cgascoig** [comment]
Hi Paul, 

Not sure this issue is fully resolved - I still get the exception after building the gem from scratch

```
Error: Could not run: cannot load such file -- acirb/top.rb
/var/lib/gems/1.9.1/gems/acirb-1.1.2.1/lib/naming.rb:71:in `get_mo_from_dn'
/var/lib/gems/1.9.1/gems/acirb-1.1.2.1/lib/loader.rb:56:in `load_hash'
/var/lib/gems/1.9.1/gems/acirb-1.1.2.1/lib/loader.rb:48:in `load_json'
/var/lib/gems/1.9.1/gems/acirb-1.1.2.1/lib/loader.rb:44:in `load_json_str'
...
```

Seems that genrubyfrompy.py is still mixing case - the autoload is setup as "acirb/" (from line 176):

``` python
def getRubyAutoLoad(autoLoaderMap):

    rubyAutoLoad = '\n'.join(['  ACIrb.autoload(\'{0}\', \'acirb/{1}\')'.format(
        rubyClass, rubyFile) for rubyClass, rubyFile in autoLoaderMap.items()])
```

whereas the generated ruby goes into "ACIrb/" (from line 247):

``` python
        fileName = os.path.join(
            os.path.abspath(
                os.path.dirname(__file__)),
            'lib',
            'ACIrb',
            pkgname +
            '.rb')
```

Thanks,
Chris

(BTW - happy to send a PR for this, but need to settle on preference for "ACIrb" vs "acirb" first )

**Comment by paullesiak** [comment]
Thanks for catching that Chris - this issue has been re-opened for tracking, but please confirm the latest commit to genrubyfrompy.py works for you.

**Comment by cgascoig** [comment]
Works for me now.

Thanks!
